name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['20.3', '21.3', '22.2']
        elixir: ['1.9.4']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
